### ISSUE TITLE
Prevent Metaspace leak in SunUnsafeReflectionProvider.fieldDictionary (or at least expose flushCache())?

### ISSUE THREAD

**Issue by mattsheppard** [x-stream/xstream#107]
If I provide XStream new dynamically generated types to serialise on each request, I seem to get a process which grows in metaspace forever (or eventually throws an OutOfMemoryError error if I set a maximum bound on metaspace).

I created an example project to exhibit this at https://github.com/mattsheppard/XstreamMetaspaceLeak (it uses groovy to generate the dynamic classes because that's what the application I originally found the problem in used, but it doesn't appear to be groovy specific).

I stumbled across `SunUnsafeReflectionProvider.fieldDictionary.flushCache()` after exploring some heap dumps, and calling that every once-in-a-while seems to be sufficient to run more-or-less indefinitely, however I can only do so by reflecting in and hacking around to get access to the protected field.

Would it be possible to either address the underlying problem by limiting the size of that fieldDictionary cache, or maybe making the references weak so the GC can collect them?

If not, would it be possible to provide some official way to flush the cache manually?

**Comment by mattsheppard** [comment]
After some digging, I also found that if `xstream.autodetectAnnotations(true);` is used, AnnotationMapper.annotatedTypes causes a leak under this test.

Looks like AnnotationConfiguration is deprecated, so maybe all that code is going away anyhow, but if not it would be nice if that were also bounded in some way (or exposed so it can be cleared easily).

I've added that to the example project above.

**Comment by joehni** [comment]
Thanks for heads-up. Actually the XStream facade should have a XStream.flushCache() method that internally flushes the caches of all its internal elements. Unfortunately it is not completely implemented.

Regarding FieldDictionary.flushCache() you can already access it if you provide the FieldDictionary yourself:

```java
FieldDictionary dictionary = new FieldDictionary();
XStream xstream = new XStream(JVM.newReflectionProvider(dictionary));
```

However, there's currently no workaround for the leak in the AnnotationMapper. All you can currently do is to delete and recreate the XStream instance from time to time.

BTW: The AnnotationConfiguration interface is only a helper construct to build XStream with JDK 1.4 and can therefore go away.

**Comment by mattsheppard** [comment]
Ah, thanks - Yeah, creating our own FieldDictionary to pass in and retain access to it would work.

I can see how dropping and recreating XStream as a whole is a possible solution - Unfortunately in my real case Spring has passed it out all over the place, which makes it tricky to actually implement (unless there's some spring magic I'm unfamiliar with). Possibly I can try to wrap XStream at creation time, pass all the method calls through but occasionally drop and recreate the underlying XStream instance.

In the long run, is there any prospect of making these things bounded or having them only keep weak references to the types?

**Comment by joehni** [comment]
Hmm. I had a closer look regarding the _leak_ in AnnotationMapper. Actually this isn't one - at least not in the sense of FieldDictionary. The information kept in the dictionary is actually a cache. If you flush it, it will rebuild itself automatically as required on request. In contrast the AnnotationMapper keeps a list of all processed types to prevent that an annotation is processed twice for a type triggering all kind of configuration changes (which will be preserved again). So, this is **no** cache. A WeakHashMap will also not help, since the configured types are kept elsewhere in XStream's configuration also.

How does the JVM get rid of the generated classes normally? If you generate new types with no end, the JVM must be able to purge them. Do you use different classloaders? In that case you should use one XStream instance per classloader also. I am not familiar with Spring, but those IoC implementations often provide different factory implementations to create objects and I guess there's also one in Spring to create an instance per classloader.

**Comment by mattsheppard** [comment]
Yeah, as I understand in that test project, Groovy is creating a new classloader whenever it reloads a class file that has changed (so in this case once per 1000 classes) - From that reload-point on the only references I could see in a heap dump to the old classloader's classes were in AnnotationMapper.annotatedTypes (assuming I cleared the FieldDictionary).

If I clear both of those stores (or never give the types to XStream to serialise to begin with), the JVM GCs them and the associated classloaders happily from what Visual VM show me.

I did sort of sense from the little bit of digging I did that AnnotationMapper.annotatedTypes wasn't a normal cache. From what I saw it was re-filling itself and respecting `@XStreamOmitField` annotations on classes from the parent class loader above Groovy's one when it saw them the second (or 10,000th) time, but I'm not surprised to hear that the situation's more complex than that (presumably because other annotations could have impacts outside the class they're within).


Anyhow, it sounds like my only way forward is to find some way to regularly drop and recreate XStream, and there's no appetite for changes in XStream that would avoid the need for XStream to be dropped occasionally in the scenario that test-project creates.

**Comment by joehni** [comment]
IIRC, the real reason why the Caching implementation was not completed was, when I realized that certain parts in XStream's configuration will always keep a reference to a class and all the strategies to flush caches to get rid of a classloader will fail in the end, if a single to such a class type reference is kept.

The best strategy I have seen so far to get rid of class registries (XStream can be seen as something like this) is the usage of a WeakHashMap with the classloader as key, i.e. in case of XStream something like:

```java
Map<Classloader, XStream> xstreamCache = new WeakHashMap<>();
```

Embedded in a factory providing an XStream instance based on the current classloader, it will automatically GC'ed since every class type it keeps is no longer strongly referenced.

**Comment by mattsheppard** [comment]
Yep, fair enough - Thanks for your time.
