### ISSUE TITLE
Duplicate classes in xpp3_min and xmlpull

### ISSUE THREAD

**Issue by ctrueden** [x-stream/xstream#117]
As described in [this old mailing list thread](http://xstream.10960.n7.nabble.com/org-xmlpull-v1-XmlPullParser-on-classpath-twice-td8428.html), XStream depends on both `xpp3:xpp3_min:1.1.4c` and `xmlpull:xmlpull:1.1.3.1`. They each have their own `org.xmlpull.v1.XmlPullParser` (and `XmlPullParserException`) but only the former has `org.xmlpull.mxp1.MXParser`, and only the latter has `XmlPullParserFactory` and `XmlSerializer`.

It appears that `xmlpull:xmlpull:1.1.3.4d_b4_min` is newer and has the same contents as `xpp3_min`. At least: the xstream codebase builds with `xpp3_min` dependency removed, and `xmlpull` version updated to `1.1.3.4d_b4_min`. However, I am not sure if this is the best solution, since I am not really familiar with the xmlpull library. What do you think? How can this discrepancy best be reconciled for a consistent runtime environment?

CC: @aherbert

**Comment by joehni** [comment]
I don't know who created xmlpull:xmlpull:1.1.3.4d_b4_min and uploaded it into the repository, but that version is complete nonsense.

xmlpull may only contain the API of the XML Pull Parser specification. The MXParser class is the implementation of the Xpp3 parser. If someone is to blame than the creators of xpp3 and kXml2, since both libraries contain also classes of xmlpull.

But moving a parser implementation into the API is simply brain dead.

BTW: The class files in that jar are from 2004.

**Comment by ctrueden** [comment]
@joehni Thanks for your analysis. But I do not understand the resolution—how can we resolve the duplicate classes between `xpp3_min` and `xmlpull`?

**Comment by joehni** [comment]
You may open a bug for [Xpp3](https://github.com/xpp3/xpp3). Maybe there will be a new release without those classes some day. Another option is to use the Xpp3Driver of XStream directly. Then you can omit the xmpull jar.

**Comment by aherbert** [comment]
I've had a look at the public methods exposed (using javap) in xpp3 and xmlpull for the two classes:

   org/xmlpull/v1/XmlPullParser.class
   org/xmlpull/v1/XmlPullParserException.class

They are identical. 

XmlPullParser is an interface. So ignoring the duplicate classes, given they are identical in their java signature, should be fine.  

XmlPullParserException is a class. So it could be different in the implementation. However this is unlikely. It is more likely that it is a copy.

The xmlpull website ([http://www.xmlpull.org/](http://www.xmlpull.org/)) is old (last change circa 2004). It is just a specification for accessing XML. There is a link to the source API where the exception is given as:

[XmlPullParserException.java](http://www.xmlpull.org/v1/download/unpacked/src/java/api/org/xmlpull/v1/XmlPullParserException.java)

However this has additional constructors from the class packaged in the Maven archive. 

The link you provided for xpp3 doesn't provide a jar file containing anything when maven is invoked, and fails to build with ant due to missing directories. It may be a work-in-progress. The [XPP3](https://www.extreme.indiana.edu/xgws/xsoap/xpp/) website allows full source to be downloaded. However this does not build using the ant build system due to missing directories from CVS. The website does not provide a link to the CVS repo where the full contents can be downloaded.

However the source download does contain inside it the full Java source of xmlpul, including an XmlPullParserException.java that matches the binary class signature. 

I copied the following folders from the XPP3 downloaded tarball to the Githib project, e.g.:

cp -r [tarball]/src/java [tarball]/src/xml [git]/src/

Then the Github project builds. So it is missing part of the original CVS source. The output jars (xpp3 and xpp_min) contain the xmlpull classes XmlPullParser and XmlPullParserException.

My conclusion is that xpp3 (and xpp3_min) is compiled to contain the dependencies of xmlpull that it requires. 

Given that it is your recommendation to omit xmlpull then this is the option I will choose. If XStream ends up using the other two classes from xmlpull, namely:

   org/xmlpull/v1/XmlPullParserFactory.class
   org/xmlpull/v1/XmlSerializer.class

then I will get a runtime error and try the alternative of including both xmlpull and xpp3_min and ignoring the duplicate classes.

As to where to submit the bug about the duplicate class clash then I will try Github. The suggested mailing list of the XPP3 website does not exist. It is possible the author Aleksander Slominski has left Indiana University.

CC: @aslom

**Comment by joehni** [comment]
Well, AFAICS @aslom is Aleksander Slominski and the Github project is the "official" one.

**Comment by MadRatSRP** [comment]
Duplicate class org.xmlpull.v1.XmlPullParser found in modules jetified-xmlpull-1.1.3.1.jar (xmlpull:xmlpull:1.1.3.1) and jetified-xpp3_min-1.1.4c.jar (xpp3:xpp3_min:1.1.4c)
Duplicate class org.xmlpull.v1.XmlPullParserException found in modules jetified-xmlpull-1.1.3.1.jar (xmlpull:xmlpull:1.1.3.1) and jetified-xpp3_min-1.1.4c.jar (xpp3:xpp3_min:1.1.4c)

Using latest version of xstream

**Comment by richanshah** [comment]
getting Same issue

**Comment by joehni** [comment]
No wonder, those artifacts have not been updated.
