### ISSUE TITLE
JPMS module support

### ISSUE THREAD

**Issue by rgoldberg** [x-stream/xstream#120]
It would be nice for XStream to easily support Java 9+ JPMS modules.

Can you:

1. either:
   1. add a `Automatic-Module-Name:` to `META-INF/MANIFEST.MF`
   2. fully modularize your code
2. not have two dependencies that both include the same package, e.g. `xpp3_min` & `xmlpull`, which can be resolved many ways:
   1. if the jars are all different optional service implementations, put the different implementations in separate jars with no implementation in the core jar (or, possibly, the core jar could contain an implementation based solely on Java SE API classes (like StAX)).
   2. just use `xpp3` instead of two jars that contain different versions of the same package that semi-overlap (this might cause classpath / class loading issues outside the module path)
   3. package a single combined `xpp3_min` & `xmlpull` jar

PS: [your FAQ](http://x-stream.github.io/faq.html#Compatibility_JRE) states that:

> All dependencies are optional

But `xmlpull ` is not marked as `optional` in the POM.  I assume the POM is correct & the FAQ is wrong, but I don't know for sure.

**Comment by joehni** [comment]
This is all not as easy as it seems. If I add the Automatic-Module-Name, XStream will be part of the module classloader and will fail, because it uses internal stuff of the JDK that has still no official replacement.

Yes, it is unfortunate that the [xpp3_min contains parts of the XML Pull API](https://github.com/xpp3/xpp3/issues/2), but I don't control 3rd party libraries. XML Pull is the the default parser of XStream and Xpp3 the standard XML Pull implementation. E.g. Android runtime provides a different XML Pull implementation and by using the XmlPullParserFactory of the API, it depends simply on the registered service for XML Pull.

The FAQ is right. Depending on your selection of the XML parser, you will have no or other required dependencies. The POM simply reflects the default usage.

**Comment by martinm1000** [comment]
> because it uses internal stuff of the JDK that has still no official replacement

Is that still the case today, with Java 10 and 11 available ?

**Comment by ge0ffrey** [comment]
Releasing XPP3 and XMLPull 1.2.0 would probably fix most of these issues, see dicussion: https://groups.google.com/forum/#!topic/xstream-user/CILJGN_vN1w

**Comment by Sineaggi** [comment]
I checked the latest release (1.4.20) and the main xstream jar doesn't appear to have an `Automatic-Module-Name`.

**Comment by Sineaggi** [comment]
Ah, the `Automatic-Module-Name` was added but a new release hasn't been made in 4 years.

**Comment by Sineaggi** [comment]
The groupId is still set to `com.thoughtworks.xstream`, would it make sense to have the `Automatic-Module-Name` to `com.thoughtworks.${jar.module.name}`?

**Comment by joehni** [comment]
It's in the master branch and it is set to "xstream," since that is also the name generated for 1.4.x that does not contain the manifest entry.

**Comment by Sineaggi** [comment]
> since that is also the name generated for 1.4.x that does not contain the manifest entry.

Makes sense. The manifest changes have been in for 4 years now tho, wouldn't it make sense to back-port it to the 1.4 line?
