### ISSUE TITLE
Security issue request to upgrade to 1.5

### ISSUE THREAD

**Issue by Shelphi** [x-stream/xstream#154]
When will the following security issue be resolved with version 1.5
https://nvd.nist.gov/vuln/detail/CVE-2013-7285#vulnCurrentDescriptionTitle

**Comment by joehni** [comment]
Sorry, but I Don't understand the question. The CVE identifies explicitly all vulnerable versions.

**Comment by niksbansode** [comment]
let me try to rephrase this question, CVE-2013-7285 vulnerability has been found for version 1.4.10. Though workaround is available [here](https://x-stream.github.io/CVE-2013-7285.html), we want to know under which version of the jar, this vulnerability would be fixed.

**Comment by joehni** [comment]
No. It has been reported for 1.4.6 and the workaround is for those versions or below. XStream contains a [security framework](http://x-stream.github.io/security.html) starting with version 1.4.7 where you can configure which Java types are handled. By default XStream does no longer deserialize types of the Java runtime, that can be used for this attack. However, this default is only in use, if the security framework has not been configured, despite all warnings. In version 1.4.10 this default failed due to a logical error.

However, the default prevents only the usage of types from the Java runtime, it makes no assumptions about any other class in your classpath, that might be used also to inject something bad. On top of it, you can configure the security framework to allow all types.

The vulnerabilty depends therefore on the programmer who made use of XStream. Just replacing the jar might keep you in a false security.
