### ISSUE TITLE
Unneeded contention in StringConverter

### ISSUE THREAD

**Issue by doublehero** [x-stream/xstream#169]
Hi,

com.thoughtworks.xstream.converters.basic.StringConverter#StringConverter uses a synchronized Map, which produces a lot of contention with parallel threads.

    public StringConverter(int lengthLimit) {
        this(Collections.synchronizedMap(new WeakCache()), lengthLimit);
    }

like https://github.com/x-stream/xstream/issues/2, we can change synchronized Map to ConcurrentHashMap.Thank you.

**Comment by zeshuai007** [comment]
Hi! I read the results of the string converter benchmark tests without cache, intern, ConcurrentMap, weakcache. The throughput of weakcache and ConcurrentMap is not much different. It is possible to replace it with concurrenthashmap. If the number of threads is large enough, I am very optimistic about concurrenthashmap. Because now StringConverter is a weak cache for synchronization.

**Comment by zeshuai007** [comment]
1. Delete the synchronized of StringConverter and replace the map with concurrentMap to reconstruct WeakCache.
2. Delete the synchronized directly in StringConverter and replace WeakCache with concurrentMap.
Which is more suitable?

**Comment by zeshuai007** [comment]
I think the second option, whether Weakcache should exist, is another issue worth discussing.
Hi! @joehni  what do you think?

**Comment by joehni** [comment]
It depends completely on the use case.

**Comment by joehni** [comment]
You can already use the Map implementation of your choice. The StringConverter provides therefore constructors taking a map. Just register that StringConverter instance on top. But, as already said, it depends completely on your use case.

XStreams documentation recommends to use the XStream instance as a static, so you avoid the expensive initialization. Therefore XStream guarantees (for its own converters) that you can marshal/unmarshal with this instance concurrently. The String converter tries to minimize the amount of required memory used for strings by sharing them, since XML often contains the same string values over and over again. However this assumption might or might not be true for the specific use case, but XStream cannot know.

Therefore, if you use such a static instance e.g. in a web application that is supposed to be 24/7 alive where you process constantly XML that contains normally only individual values, XStream requires a possibility to get rid values that are no longer used, otherwise it might cause an out of memory situation.

XStream's defaults try to be as aggressive as possible without breaking an application in any case. Therefore the default cannot get rid of the weak references and synchronization. If you know your use case, you might use already a ConcurrentMap implementation if you know that the life time of the XStream instance is limited or your XML will never contain such a variety of string values or you might eben use a normal HashMap if you know that you will not unmarshal concurrently.
