### ISSUE TITLE
Is it possible to use XStreamImplicit with custom collection?

### ISSUE THREAD

**Issue by user753** [x-stream/xstream#182]
I am using xstream with Scala and everything works fine, I have ListConverter for Scala List class, but when I try use XStreamImplicit with List 
```
@XStreamImplicit
items: List[Item]
```
I get an error
```
 Field "items" declares no collection
```
Because List doesn't implement `java.util.Collection`
Is there any workaround?

**Comment by joehni** [comment]
Unfortunately, no. See, each converter is responsible for the contents within its container, e.g. a ListConverter will render the items of the list, but expects to be embedded into an own element.

The complete implicit stuff is some kind of hack embedded in the reflection-based plugins. Because of the missing parent, the converter has no idea of the original collection type. When it processes an unknown element (i.e. an element that cannot be mapped to a member of the current type), it will look for declared implicit collections (List, Map, array) and it will use at deserialization time default types (not necessarily original one: ArrayList, HashMap) for the collection to fulfill the contract. Therefore it is not even possible to use arbitrary types derived from List.

Your only possibility in this case to support such a format is to write a custom converter for the complete object that contains the list.
