### ISSUE TITLE
Can i use @XStreamAlias with setter/getter method?

### ISSUE THREAD

**Issue by iamsxm** [x-stream/xstream#205]
i hava base class like:
```
public class baseCar{

    private String color;

    private String name;

    //setter
    //getter
}

```
and a child lass like:
```
public class bmw extends{

    private String color;

    private String name;

    @XStreamAlias
    @overrid
    public setColor(string color){
        this.color=color;
    }
    //others
}
```
so, i can map different XML into the same class.
Can i use @XStreamAlias with setter/getter method?

**Comment by joehni** [comment]
Hi,

by default XStream does not use getters or setters at all, the fallback converter is based on reflection and writes directly into the instance. You can register the JavaBeanConverter either individually for special types or as fallback. That one will use getters and setters.

An alias definition makes only sense, if you actually define a different name for the member. However, there's a caveat for the JavaBeanConverter, because the @XStreamAlias is defined for fields only, i.e. the definition is only useful if the field name matches the bean property name. Otherwise you have to use XStream's methods to define an alias for the type's property name.
