### ISSUE TITLE
"java7" was renamed to "jdk7" in 1.4.14 but docs haven't been updated

### ISSUE THREAD

**Issue by daniel-beck** [x-stream/xstream#225]
List of releases:
https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/

https://x-stream.github.io/faq.html#Compatibility_Android mentions -java7, as does the last download link on https://x-stream.github.io/download.html; possibly other locations.

**Comment by jglick** [comment]
Also, not sure if it is too late to change how this variant is managed, but: https://github.com/jenkinsci/jenkins/pull/5077#issuecomment-732989372

**Comment by jglick** [comment]
Hmm, seems to be deliberate, though I believe this is misusing Maven conventions: https://github.com/x-stream/xstream/issues/112#issuecomment-378057723 https://github.com/x-stream/xstream/issues/98#issuecomment-335903886

Prior to multirelease JARs in Java 9, I would expect Java 8-specific code to live in its own artifact with a dependency on a 7-compatible artifact containing most of the code.

**Comment by joehni** [comment]
That was a pure oversight. Expect the -java7 version to appear in a view hours in Central.

XStream had always mixed class versions in its jar. Actually the -java7 version should only be used if the target runtime fails, because it scans all classes of the normal jar. XStream itself will never load a Java 8 class in a Java 7 runtime environment.
