### ISSUE TITLE
De-serializing arbitrary JSON fields into a POJO with Map field

### ISSUE THREAD

**Issue by flatlanderer** [x-stream/xstream#229]
I have this test JSON object, that needs to be deserialized into a POJO

```json
{
  "entity": {
    "aclWrite": [
      {
        "entityId": "0-0"
      }
    ],
    "aclRead": [],
    "publicWrite": false,
    "publicRead": true,
    "birthdate": -382924800000,
    "address": "1793 Britton Rd",
    "nickname": "Karen",
    "email": "eo'neill27@ma1l2u.org"
  }
}
```

The POJO that will be holding this data:

```java
@XStreamAlias("entity")
public class EntityDTO {
  private String entityType;
  private String entityId;
  private List<EntityStub> aclRead;
  private List<EntityStub> aclWrite;
  private Boolean publicRead;
  private Boolean publicWrite;
  // Other arbitrary fields will be injected here:
  private Map<String, Comparable> properties;
}
```

The JSON fields not mapped with the POJO by XStream annotations should be all injected into the "properties" map: *birthdate, address, nickname* and *email*

I have this simple deserializer:

```java
public static <T> T deserialize(String json, Class<T> tClass) {
 if(Objects.isNull(json)) {
   return null;
 }
 XStream xstream = new XStream(new JettisonMappedXmlDriver());
 xstream.processAnnotations(tClass);
 T model = (T) xstream.fromXML(json);
 return model;
}
```

Used like: `EntityDTO entity = deserialize(theJSONString, EntityDTO.class);` but the problem is XStream is complaining that `No such field` for *birthdate, address, nickname* and *email* which is expected, so, in what way XStream can be configured to automatically inject unmapped fields into the "properties" map? 

I've tried to create a custom converter that will do the inverse just to test things out:

```java
public class EntityConverter extends ReflectionConverter {
  public EntityConverter(Mapper mapper,
      ReflectionProvider reflectionProvider) {
    super(mapper, reflectionProvider);
  }
  @Override
  public void marshal(Object source, HierarchicalStreamWriter writer, MarshallingContext context) {
    EntityDTO entity = (EntityDTO) source;
    entity.getPropertyMap().forEach((s, comparable) -> {
      writer.startNode(s);
      // TODO: Store as the correct JSON value not just string
      writer.setValue(String.valueOf(comparable));
      writer.endNode();
    });
    entity.setPropertyMap(null);
    super.marshal(source, writer, context);
  }
  @Override public Object unmarshal(HierarchicalStreamReader reader, UnmarshallingContext context) {
    // TODO: 
    throw new UnsupportedOperationException("Not supported yet.");
  }
  @Override public boolean canConvert(Class type) {
    return EntityDTO.class.isAssignableFrom(type);
  }
}
```

The problem with this approach is the writer can only write values as String thus causing the output JSON not to match the correct field types, all are String.

**Comment by joehni** [comment]
As you already found out: You will have to write a custom converter to support such a map with arbitrary elements.

For a better understanding: XStream writes XML. It is Jettison that exchanges the format under the hood.

writer.setValue() will write an XML element's value. This is a string. Always. A converter will write here the string representation of the object's value, a value it can deserialize later again.

Have a look at the example for a complex converter in the [Converter Tutorial](https://x-stream.github.io/converter-tutorial.html#ComplexConverter). That example writes the elements using the MarshallingContext, which is able to select the appropriate converter for another (embedded) object.

BTW: It is a bad idea to derive from ReflectionConverter in this way. When a converter's marshal-Method is called, it expects to be in the context of the parent element, because it may and will write XML attributes. However, you already write child elements and thus closing the parent element implicitly. The result is an indefinite state when you call super.marshal(). Deserialization will definitely never work.
