### ISSUE TITLE
Getting NoSuchMethodError with XStream.getClassMapper()

### ISSUE THREAD

**Issue by jcgg70** [x-stream/xstream#236]
I am seeing an error on the server logs, any clue what may be causing this?

org.apache.cxf.interceptor.Fault: Unexpected Error
java.lang.NoSuchMethodError: com.thoughtworks.xstream.XStream.getClassMapper()Lcom/thoughtworks/xstream/alias/ClassMapper;

I have a jar which was provided and is calling this method, the line I identified is this:
(I believe that jar is using xstream-1.0.2.jar)

 this.xstream.registerConverter(new XstreamArrayListConverter(this.xstream.getClassMapper(), "XYZListConverter"));

JDK 1.7
JBoss EAP 5.2
cxf version: 2.6.2
xstream: 1.4.14-jdk7 -- current xstream version in my project, best guess is that because of the incompatibility with the jar provided one this won't work; however I am not sure the jar can be modified as it does not belong to me.

**Comment by joehni** [comment]
Well, XStream 1.0.2 is 16 years old, that method was deprecated in the 1.2.x versions and finally removed for 1.4 (9 years ago). The question is, what is the main reason to use a newer XStream version here, since the rest of the stuff seems ancient also. If you're concerned about the CVEs, it seems you're out of luck (and I believe your other dependencies will have more securtity issues as well).

Either you have the possibility to modify that call above or you must have the possibility to register an own Converter that prohibits the deserialization of the problematic types using the workaround described the the latest CVEs for XStream 1.4.6 or below.

If you have no access to the code creating that XStream instance, your last resort is a private version of XStream as fork of XStream 1.0.2 (or 1.3.1, the last one with that method) and register the "security" converter from above in the constructor code.

**Comment by jcgg70** [comment]
Thank you for your reply, yes trying to address CVEs, please provide the URL of the workaround you are referring to and any helpful resources on the option of using my own converter. I know this is ancient, actually upgraded from and older JBoss and JDK

**Comment by joehni** [comment]
The workaround is part of the [CVE](https://x-stream.github.io/CVE-2020-26258.html#workaround) description.
