### ISSUE TITLE
When called through Swagger 2.0 generated API with JSON content, XStreamJSONMessageConverter:readInternal ends in CannotResolveClassException, taking a tag name for a class it attempts to load

### ISSUE THREAD

**Issue by mlebihan** [x-stream/xstream#240]
Using a Java client generated by the _Swagger_ API to call a _Geoserver_ REST service, I encounter a _CannotResolveClassException_.

In a debug session of that server, it appears that _XStream_ is taking the name of a JSON tag as a class name that it attempts to load in a `Class.forName` statement that fails.

The whole incident with the debug session including _XSteam_ statements in `1.4.11.1` version (but they haven't changed for this subject in the current 1.4.15) [is described on GIS Stackoverflow here](https://gis.stackexchange.com/questions/385773/geoserver-rest-api-call-to-workspacesapi-postworkspaces-fails-in-a-cannotresolve) : look a the problem in it's question, and the debug session done in an answer on it. Thanks !

**Comment by joehni** [comment]
First: XStream committers are not involved in the GeoServer project and personally I don't know what the XStreamJSONMessageConverter does.

XStream is a project to serialize a Java object into XML and back. The resulting XML structure is specific to XStream and contains anything to recreate the original object. It is possible to configure XStream to some extend to tweak the structure, but it still has to contain all information for the object's recreation. This implies that the XML contains also the required class types. This is how XStream works and what it was designed for.

XStream contains a Jettison adapter that utilizes the StAX driver to emit and read JSON instead of XML, but still the structure is XStream specific. If someone wants to read JSON defined by an OpenAPI definition, someone will have to configure XStream properly. I can't tell if this "someone" is you or the GeoServer developers, but its definitely not XStream's task. On top of it, it is not possible to express in JSON anything that is part of the XML format, i.e. the functionality is limited if using JSON.

**Comment by mlebihan** [comment]
I'm not in the _Geoserver_ developer team neither, I'm just encountering a bug and I try to find it's cause.
I didn't noticed that the two first statements executed at the beginning of it's story, below, were written in `org.geoserver` and not `com.thoughworks`, sorry.

```java
    public Object readInternal(Class<?> clazz, HttpInputMessage inputMessage)
            throws IOException, HttpMessageNotReadableException {
    /* > */  XStreamPersister p = xpf.createJSONPersister();
        p.setCatalog(catalog);
        if (inputMessage instanceof RestHttpInputWrapper) {
            ((RestHttpInputWrapper) inputMessage).configurePersister(p, this);
        }
        return p.load(inputMessage.getBody(), clazz);
    }
```

```java
    public XStreamPersister createJSONPersister() {
        return buildPersister(new JettisonMappedXmlDriver());
    }
```

It changes the problem, that's true. I don't know if the maintainer of the code known that he was using an internal part of _XStream_, that (if I'm understanding well what you wrote) is more designed to handle XML to JSON translation.

**Comment by joehni** [comment]
Well, the JettisonMappedXmlDriver is part of XStream, but it is designed to read JSON (with some limits) that was also written by it before. Without further configuration it will never match an arbitrary OpenAPI definition.
