### ISSUE TITLE
Relevant commits for CVE-2021-213{41-51}

### ISSUE THREAD

**Issue by utkarsh2102** [x-stream/xstream#244]
Hello,

Thanks for taking care of this for so long and also for fixing CVEs at the earliest!

However, it's not very clear at the first glance as to what the relevant fixes of the CVE-2021-213{41-51} are. I'd like to patch/backport these fixes to the older version (1.4.11.1) for Debian stretch and it'd be also really helpful for other downstream maintainers if this issue could help in locating the relevant commits that fixed those CVEs. Hope this makes sense and you can help us with that.

Thanks in advance! 😄

**Comment by joehni** [comment]
Hi,

the relevant commit was d5e51177634afea7213b9dc2d21f101d2e258db9 which covered all CVEs at once. However, the 1.4.x line is meant to be binary compatible, so I don't see why you want to do this. XStream itself uses XSite to generate its documentation which uses in turn an old XStream (1.4.4) release. We simply overwrite the dependency in our build with a new version.

The main compatibility issue arises by the types, that are now blocked, but that was the point of the fix for the CVEs. You will simply backport this.

Regards,
Jörg

**Comment by joehni** [comment]
Was accitentally linked with wrong pull request
