### ISSUE TITLE
1.4.17 CVE fixes

### ISSUE THREAD

**Issue by tcullum-rh** [x-stream/xstream#267]
Hi,

Thanks for all of your hard work on xstream and especially with addressing security issues, providing workarounds, detailed pages, etc...

Reference: https://x-stream.github.io/security.html table section `Version 1.4.17`:

There are eight CVEs that all have the same description:

> XStream is vulnerable to an Arbitrary Code Execution attack.

In order to properly track these, my question is: are these, and/or any subset of the list of CVEs fixed in 1.4.17, all fixed by the same patch? The CVE Program's CNA rules state that multiple CVEs should be assigned for "independently fixable" issues[1]. So, if the same code patch (not workaround) always fixes multiple issues, then the issues all correspond to one CVE.

Looking at the CVE pages on x-stream.github.io, it seems that each attack vector has its own CVE, but I want to clarify that these are also all independently fixable distinct code issues, or if they are all fixed by the same code patch.

I've also seen https://github.com/x-stream/xstream/issues/244  and this may be a valid question for that series as well.

Thank you.

1. https://cve.mitre.org/cve/cna/rules.html#section_7-2_how_many_vulnerabilities

**Comment by joehni** [comment]
Until version 1.4.17 XStream provided by default an internal blacklist for types in the Java runtime that can be used for malicious actions. Each report describes an individual vector not handled by that blacklist. So, yes, you could provide an individual workaround for each reported CVE. The number of physical commits is irrelevant here.

However, since it does not make sense to force the users of XStream to read all of the CVEs just to collect the individual actions for a workaround, the security page provides one workaround that covers all the CVEs by blacklisting the individual stuff.

And, yes, with the latest version 1.4.18, XStream switched to a whitelist by default. However, this would have prevented the reported issues in all CVEs, not only the new ones.

**Comment by tcullum-rh** [comment]
Thank you very much @joehni .
