### ISSUE TITLE
Facing lot of regression after upgrading to 1.4.19 from 1.4.17

### ISSUE THREAD

**Issue by sagga001** [x-stream/xstream#286]
Hi,
Problem :
I have upgraded to 19 version and most of the test cases around 429 are in failure due to error NoTypePermission.I also implemented allowtypehierarchy for them and could resolve significant number of them but I am stuck with 30-40 test cases in which I can't add allowtypehierarchy as class is in other package.It starts giving me cyclic dependency issue.Now we dont want to do refactoring of project which is again a huge effort.
I also tried adding object in calling classes but then again go stuck with some issues.
Question:
Can you pls suggest any common way to come out of it? Like where ever xstream is instantiated there I can pass common object with loaded white list.Or any property in xstream

**Comment by joehni** [comment]
Hi,

sorry, but I see no problem. The TypeHierarchyPermission is the only one that actually keeps a type, all other operate on plain strings. So where should any problem arise with cyclic dependency issues?

Regards,
Jörg

**Comment by sagga001** [comment]
Yes the problem arises as the classes are in different package so instead of doing refactoring I am looking out for a solution to fix at common place.Now I tried fixing in the calling class itself but passing xstream object at all places where it was called but then got stuck as xstream is instantiated in anonymous class as well.

See like below even If I pass xtsream object in the called method with allowtype hierarchy then it can be instantitated again somewhere in anonymous class like below

 else{
                xStream = new XStream() {
                    protected MapperWrapper wrapMapper(MapperWrapper next) {
Any suggestion what we can use for it..Refactoring it is too much otherwise

**Comment by sagga001** [comment]
See in order to avoid refactoring and allow the class from other module itself I tried below options but none solved it,not even .*
Please suggest on it.
[13:21] Aggarwal, Sonia (Nokia - IN/Gurgaon)
xstream.allowTypesByWildcard(new String[] {
"com.alcatel.ni.inspectionsystem.**","com.alcatel.expert.**","com.alcatel.util.**","com.alcatel.beliefnetwork.**"
});
xstream.allowTypesByWildcard(new String[] {
"com.alcatel.**"
});
xstream.allowTypesByWildcard(new String[]{"*.class"});
xstream.allowTypesByWildcard(new String[] {
"na-na.src.main.java.com.alcatel.**"
});
xstream.allowTypesByWildcard(new String[]{"*.MdfSeltScenarioConclusion.class"});
xstream.allowTypesByRegExp(new String[]{".*"});
xstream.allowTypesByRegExp(new String[] {
".*\\na-na\\com\\.alcatel\\..*"
});
xstream.allowTypesByRegExp(new String[]{"*.class"});
xstream.allowTypes(new String[]{"*.class"});

**Comment by joehni** [comment]
Your second call supercedes the allowed types of the first call.
Your third call is useless. XStream operates on class names, not on file names, you cannot have a class names "class".
Your forth call looks dubious, I cannot imagine that you have class types beginning with "n-n.src.main.java."
Your fifth call is again a file pattern useless for a class name.
Your sixth call allows XStream to unmarshal every class superseding all previous rules and opens the unmarshalling process for all known security issues.
Your seventh to ninth calls again operate on file name patterns.

Every XStream instance keeps its own list of TypePermission objects, because typically you use one instance for each marshalling scenario (= defined XML data). The XStream instance is normally setup once and reused for the marshalling. However, typically you handle different types for different marshalling scenarios, therefore the XStream instances keep their own list.

If you create XStream instances on the fly, they will have to be initialized properly for your scenario. However, creating new XStream instances for the same scenario over and over again, is probably not the best approach, see [FAQ](https://x-stream.github.io/faq.html#Scalability_Thread_safety).

**Comment by sagga001** [comment]
Fixed..

**Comment by sagga001** [comment]
I was expecting some useful comment here related to usage of Xstream. Nothing can be done if in existing projects there is regression because of new versions of Jars.There should have been some common fix or check that can be done in utility or property file to avoid refactoring..
