### ISSUE TITLE
New version published

### ISSUE THREAD

**Issue by punkdis** [x-stream/xstream#307]
the team has published 1.4.19 on 29JAN22 https://x-stream.github.io/changes.html 

there has been commits from 2 months ago that fixes some items. Is there a plan to release the next version of xstream?

**Comment by ccac001** [comment]
Hi guys,
Really would appreciate an answer over this question since we see that in master exists some fixes for some issues:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50393
https://github.com/x-stream/xstream/issues/296
https://osv.dev/vulnerability/OSV-2022-749

And it's worth to mention that some of those issues impacts the usage of components like eureka-client.

So, are you planning to release a new version soon? 

Thanks in advance.

**Comment by BrahianVT** [comment]
any update on this?  @joehni  you know something about this?

**Comment by joehni** [comment]
This simply depends on my spare time.
