### ISSUE TITLE
outer-class not found when a class could be static in JDK21

### ISSUE THREAD

**Issue by NicholasWMRitchie** [x-stream/xstream#366]
Long ago I made a small mistake.  I didn't declare an inner class as static when I should have.  As a result, XStream wrote out an unnecessary outer-class tag when it serialized the class.

This became a problem recently.  It appears that JDK21 notices that the inner class could be static and doesn't include the hidden reference to the outer class (no "OuterClass.this).  It is as though the compiler automatically added a "static" modifier to the class definition.   

Now when I go to deserialize an object I wrote long ago, the XML contains an "outer-class" tag.  However, the new optimized .class file without the "OuterClass.this" can't read in the old non-static version of the class.  The new reader doesn't know what to do with the \<outer-class\> tag.

An ad-hoc solution is to add a bogus reference to the outer-class in the inner-class to disallow the compiler from "helpfully" adding a "static" tag to the class and optimizing away the "OuterClass.this" reference.

**Comment by joehni** [comment]
Since you claimed the non-static inner class as mistake, I guess the solution is to get rid of the outer-class element. So, declare the inner class as static. Add a member (e.g. "outerClassDummy") to it of arbitrary type (e.g. Stgring) and declare it as transient. Configure XStream to use a field alias named "outer-class" for this member:
```java
xstream.aliasField("outer-class", Inner.class, "dummy");
```
The transient declaration will ensure that the field is never written again for Inner. The configuration ensures that for any legacy XML containing the "outer-class" as member it is ignored when unmarshalling Inner, i.e. your new setup is backwards compatible for existing XML files.
