### ISSUE TITLE
pom.xml refers to non-existent surefire plugin version

### ISSUE THREAD

**Issue by snormann** [x-stream/xstream#48]
Shouldn't line 849 in pom.xml

      <version.plugin.maven.surefire>2.4.3</version.plugin.maven.surefire>
be this instead:
   <version.plugin.maven.surefire>2.19.1</version.plugin.maven.surefire>
?

2.4.3 of surefire plugin doesn't exist.  In any case, until I changed the version to 2.19.1, I could not build.

**Comment by khmarbaise** [comment]
maven-surefire-plugin [version 2.4.3 does exist](http://search.maven.org/#artifactdetails%7Corg.apache.maven.plugins%7Cmaven-surefire-plugin%7C2.4.3%7Cmaven-plugin) but of course it is ancient version..and should be replaced with a newer one as you suggested...

**Comment by joehni** [comment]
Why upgrade, it just works! If you look at the manifest of 1.4.9, you'll see that I used Maven 3.3.9 to release XStream 1.4.9 last week:

    $ catmf ~/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.jar
    Manifest-Version: 1.0
    Archiver-Version: Plexus Archiver
    Created-By: Apache Maven Bundle Plugin
    Built-By: joehni
    Build-Jdk: 1.8.0_74
    Specification-Title: XStream Core
    Specification-Vendor: XStream
    Implementation-Title: XStream Core
    Implementation-Version: 1.4.9
    Implementation-Vendor-Id: com.thoughtworks.xstream
    Implementation-Vendor: XStream
    Specification-Version: 1.4
    X-Build-Os: Linux
    X-Build-Time: 2016-03-15T23:14:15Z
    X-Builder: Maven 3.3.9
    X-Compile-Source: 1.5
    X-Compile-Target: 1.5

Even more, since XStream 1.4.x is compatible to Java 1.4 and according the BUILD.txt:

    For Java 6 or higher build with Maven 3.2.5 or higher
    For Java 5 build with Maven 3.0.5
    For Java 1.4 build with Maven 2.0.11

I doubt that 2.19.1 works with Maven 2.0.11 in a  Java 1.4 runtime.

**Comment by khmarbaise** [comment]
Maven Surefire Plugin Version 2.19.1 officially supports Maven 2.2.1+ and Java 1.5...as the whole line of plugins in the meantime only support Maven 2.2.1+ as lowest Maven version. [Maven 2.2.1 is officially End Of Life](http://maven.apache.org/maven-2.x-eol.html) since [February 2014](http://www.mail-archive.com/announce%40maven.apache.org/msg00575.html). 

Apart from that...making a relationship between Maven version and JDK is not the best idea. If you need to build against a particular JDK you should use [toolchains](https://maven.apache.org/guides/mini/guide-using-toolchains.html) and than it does not matter which Maven version you are using...

**Comment by joehni** [comment]
>  Maven 2.2.1 is officially End Of Life since February 2014. 

So is Java 1.4, 5 and 6 ;-)

I'll update the head before first 1.5.x release, but not the 1.4.x branch.

> If you need to build against a particular JDK you should use toolchains

XStream uses different profiles based on the JDK running the build, because e.g. some classes may be excluded for the final result (note, these are custom builds; a build for release enforces currently Java 8). I am not aware of any possibility to trigger the profiles using toolchains.
