### ISSUE TITLE
xstream:1.4.9 and 1.4.8 in Android Studio problem

### ISSUE THREAD

**Issue by YLBFDEV** [x-stream/xstream#49]
compile 'com.thoughtworks.xstream:xstream:1.4.9'

> Error:Error converting bytecode to dex:
> Cause: java.lang.RuntimeException: Exception parsing classes
> Error:1 error; aborting
> Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: > 
> 
> com.android.ide.common.process.ProcessException:
> 
> java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_71\bin\java.exe'' finished with non-zero exit value 1

**Comment by joehni** [comment]
XStream is a library with classes targeting different Java versions. Since Android does not support Java 8, the processor fails when it tried to process the classes targeting Java 8 in special. However, these classes are optional. XStream uses reflection to load them if the runtime has proper support.

Unfortunately the Android processor who prepares the classes does not know this and fails for the complete library. You can simple remove com.thoughtworks.xstream.mapper.LambdaMapper.class and com.thoughtworks.xstream.mapper.converters.reflection.LambdaConverter.class for the jar file or you checkout the sources from the 1.4.9 tag and build XStream yourself using a Java 7 runtime. Or you find a way to tell the Android processor to ignore those two classes.

**Comment by whvirgil2015** [comment]
Means that we can only use 1.4.7- versions when using Java7, if we don't want to compile the sources by ourselves.

**Comment by joehni** [comment]
Currently, yes. Or do *you* know, how to tell Android to exclude specific classes?

**Comment by joehni** [comment]
XStream 1.4.10 has also been released as XStream 1.4.10-java7. The latter does not contain any stuff of Java 8.
