### ISSUE TITLE
context.convertAnother(..) disables xstream.aliasField(..)

### ISSUE THREAD

**Issue by decoursin** [x-stream/xstream#56]
If I use `context.convertAnother` (within a Converter class) it converts it and adds it as a subnode. Yes, however, it's not referred to by the class name instead of the property name.

Example,
```
public class Node {
    SomeType SomeProperty;
}
public class NodeConverter implements Converter {
    ...
    public void marshal(Object value, HierarchicalStreamWriter writer,  MarshallingContext context) {
        Node node = (Node) value;
        node.convertAnother(node.getSomeProperty);
    }
}
```
The resulting xml will be something like:
```
<NodeConverter>
         <SomeObject>..</SomeObject>
</NodeConverter>
```
Instead of:
```
<NodeConverter>
         <SomeProperty>..</SomeProperty>
</NodeConverter>
```
As a result, `xstream.aliasField(..)` is useless / has no effect. Is this right?

**Comment by decoursin** [comment]
Being able to alias the class from the `context.convertAnother(..)` function would be a good fix.

So the api would be something like: `convertAnother(Object current, Class type, **String name**)

**Comment by joehni** [comment]
This is by design. A converter implementation is responsible on its own what it uses for the tag names of its children. A reflection-based converter uses by default typically the field name, a collection converter uses the element's type and another one uses constants (e.g. the ColorConverter). It's up to the converter implementation to respect any alias setting by requesting the current Mapper which is typically provided as an constructor argument for the converter.

**Comment by decoursin** [comment]
Ok, thank you
