### ISSUE TITLE
ReflectionConverter rarely serializes fields annotated with @XStreamOmitField

### ISSUE THREAD

**Issue by SamCarlberg** [x-stream/xstream#80]
I use XStream to serialize save files for my project, and had a user report that XStream was attempting to serialize a field annotated with `@XStreamOmitField` (issue: https://github.com/WPIRoboticsProjects/GRIP/issues/703). My fix was to mark it with `transient` as well (https://github.com/WPIRoboticsProjects/GRIP/pull/722), which fixed the problem the user was experiencing.

FWIW only one person has experienced this and I wasn't able to reproduce it on any system (Windows 8.1, Windows 10, macOS, Linux).

**Comment by joehni** [comment]
It depends how you use the annotations. XStream is basically thread-safe after configuration. However, since annotations modify XStream's setup on the fly, you will face such effects. To avoid this kind of trouble you have to preprocess the classes before you start to marshal/unmarshal your first object. See FAQ and annotation tutorial for further details.
