### ISSUE TITLE
Unknown attributes are ignored

### ISSUE THREAD

**Issue by gboersma** [x-stream/xstream#85]
When attributes appear in the XML that do not map to fields in Java, they are ignored. This is different than unknown elements, that are not ignored and cause an error.

Is there any way to have the same error for unknown attributes? I do not see an option anywhere.

**Comment by joehni** [comment]
Yes, unknown attributes are completely ignored. Attributes have been used historically in XStream only for internal stuff e.g. the _class_ attribute. Later on XStream was enhanced to support also attributes for members that use a SingleValueConverter. However, member are controlled by the individual converters. The converter implementations have no knowledge about the attributes that are used by the XStream core. Therefore you cannot make the assumption that any (for a converter) unknown attribute is an error.

**Comment by gboersma** [comment]
Makes sense. Can you add some documentation for this? This was a surprise to me when I started using XStream. Helpful to know beforehand.

I suggest inserting it near the documentation for "ignoreUnknownElement". I would also recommend that validation via DTD / XSD is highly recommended.

**Comment by joehni** [comment]
Validation can be done at parser level. However, that has historically meant to configure the DOM driver. I found now also a validating reader (as wrapper) in the XMLBeans project of Apache (in the meanwhile also no longer developed) that provides validation for StAX. Due to the streaming nature of those parsers, validation cannot be done before XStream processes the stream, the parser has to do it on the fly. Another problem will be the system attributes of XStream itself. Those are required to recreate the object graph, but are naturally not part of a foreign schema.
