### ISSUE TITLE
Multiple namespaces

### ISSUE THREAD

**Issue by teo89** [x-stream/xstream#9]
I want to have an xml like this
``` XML
<a:MD_Metadata xmlns:a="http://www.a" xmlns:b="http://www.b" xmlns:c="http://www.c" id="myId" xsi:schemaLocation="http://www.a">
	<a:fileIdA>
		<b:fieldB>myId</b:fieldB>
	</a:fileIdA>
</a:MD_Metadata>
```
But i have a lot of issues ::
first of all i can found how to remove default 
                 <?xml version="1.0" encoding="UTF-8"?>
second i can set more than one namespaces. I do that but i can found how to add more than one

         Object object = req.getObject();
		
        QNameMap nsm = new QNameMap();
        nsm.setDefaultPrefix("a");
        nsm.setDefaultNamespace("http://www.example.com");
        XStream xstream = new XStream(new StaxDriver(nsm));
        
	xstream.alias("Test", ExportXMLDTO.class);
	xstream.toXML(object);

I saw examples with new QName() but i get error
java.lang.ClassNotFoundException: javax.xml.namespace.QName not found

**Comment by joehni** [comment]
The XML you've presented above does actually not use a default namespace. Individual namespaces are declared using QName instances. QName is normally part of the JDK ... what environment are you using?

The StaxWriter writes (in contrast to all other drivers ... historical difference) normally always a XML declaration. If you want to avoid it, you have to create the StaxWriter on your own. Instead of

    XStream xstream = new XStream(new StaxDriver(nsm));
    xstream.toXML(object);

you have to use

    StaxDriver driver = new StaxDriver(nsm);
    XStream xstream = new XStream(driver);
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    StaxWriter = driver.createStaxWriter(driver.getOutputFactory().createXMLStreamWriter(baos));
    xstream.marshal(object, writer);
    baos.close();
    baos.toString(StandardCharsets.UTF_8);
