### ISSUE TITLE
Wrong usage of version numbers in Maven

### ISSUE THREAD

**Issue by mfueser** [x-stream/xstream#98]
When version ranges in Maven are used, the wrong artefact is downloaded by Maven.

**The problem**

The variant of the artefact for Java 7 is identified as the latest version by maven, which is wrong because it is a variant of the current version.
```xml
<dependency>
<groupId>com.thoughtworks.xstream</groupId>
<artifactId>xstream</artifactId>
<version>[1.4.9,)</version>
</dependency>
```

This leads to 1.4.10-java7 being downloaded instead of 1.4.10 thus resulting in a breaking build.

**Possible solution**
The same version should not be used to identify a variant of a software artefact. Instead the artefact itself should be named like e.g.

```xml
<groupId>com.thoughtworks.xstream</groupId>
<artifactId>xstream-java7</artifactId>
<version>1.4.10</version>
```

**Comment by joehni** [comment]
The version scheme was selected on purpose. Depending on a deep dependency tree, you may end up using both artifacts in different versions if the artifactId is different. Depending on the version only, everyone can easily overwrite it using a dependencyManagement section in own projects without the need for exclusions (ever managed a build with ~400 projects? I cannot tell how many excludes I had to use for bouncycastle artifacts alone). Using a dependencyManagement makes it very easy to use the same software stack for standard Java 8 development and Android.

Now, yes, I was not aware that it breaks the Maven version range, but IIRC this depends more on the latest entry in the metadata.xml on central than on this version scheme.

Personally I never found out why people are so fond of ranges in Maven, because it counteracts a reproducible build. Ever tried to fix a bug on a 5 year old customer project? Nobody wants suddenly a bunch of updated artifacts with the first build.

**Comment by joehni** [comment]
As said, the scheme was selected on purpose.
